import { CachedDevice } from '../tuya';

export interface CommandGenerator {
  /**
   * Executes the given commands for a device.
   * @param device The target device
   * @param commands A dictionary of Tuya commands generated by the AI
   * @param allDevices All available devices, useful for looking up dependencies like IR blasters
   */
  execute(device: CachedDevice, commands: { code: string; value: any }[], allDevices: CachedDevice[]): Promise<any>;
}
